/*
	Jose Garrido 13-02-10
	Para desplegar las votaciones de manera fluida.
	Se usan las funciones de jquery show() y hide().
	Ver: jquery.js	
*/

$(document).ready(function(){
		
		$("#COMPUPAPI").toggle(function(){
     		$("#votCOMPUPAPI").show('normal');
   		},function(){
			$("#votCOMPUPAPI").hide('normal');
	   	});
   		$("#COMPUGALLO").toggle(function(){
     		$("#votCOMPUGALLO").show('normal');
   		},function(){
			$("#votCOMPUGALLO").hide('normal');
	   	});
		$("#COMPUMAMI").toggle(function(){
     		$("#votCOMPUMAMI").show('normal');
   		},function(){
			$("#votCOMPUMAMI").hide('normal');
	   	});
		$("#COMPULOVE").toggle(function(){
     		$("#votCOMPULOVE").show('normal');
   		},function(){
			$("#votCOMPULOVE").hide('normal');
	   	});
   		$("#COMPUCARTOON").toggle(function(){
     		$("#votCOMPUCARTOON").show('normal');
   		},function(){
			$("#votCOMPUCARTOON").hide('normal');
	   	});
		$("#COMPUCHINAZO").toggle(function(){
     		$("#votCOMPUCHINAZO").show('normal');
   		},function(){
			$("#votCOMPUCHINAZO").hide('normal');
	   	});
   		$("#COMPUADOPTADO").toggle(function(){
     		$("#votCOMPUADOPTADO").show('normal');
   		},function(){
			$("#votCOMPUADOPTADO").hide('normal');
	   	});
		$("#COMPULOLAS").toggle(function(){
     		$("#votCOMPULOLAS").show('normal');
   		},function(){
			$("#votCOMPULOLAS").hide('normal');
	   	});
		$("#COMPUBUTT").toggle(function(){
     		$("#votCOMPUBUTT").show('normal');
   		},function(){
			$("#votCOMPUBUTT").hide('normal');
	   	});
		$("#COMPUPREGUNTON").toggle(function(){
     		$("#votCOMPUPREGUNTON").show('normal');
   		},function(){
			$("#votCOMPUPREGUNTON").hide('normal');
	   	});
		$("#COMPUMORFEO").toggle(function(){
     		$("#votCOMPUMORFEO").show('normal');
   		},function(){
			$("#votCOMPUMORFEO").hide('normal');
	   	});
		$("#COMPUCHACARRON").toggle(function(){
     		$("#votCOMPUCHACARRON").show('normal');
   		},function(){
			$("#votCOMPUCHACARRON").hide('normal');
	   	});
		$("#COMPUPRODUCTISTA").toggle(function(){
     		$("#votCOMPUPRODUCTISTA").show('normal');
   		},function(){
			$("#votCOMPUPRODUCTISTA").hide('normal');
	   	});
		$("#COMPADRE").toggle(function(){
     		$("#votCOMPADRE").show('normal');
   		},function(){
			$("#votCOMPADRE").hide('normal');
	   	});
		$("#COMADRE").toggle(function(){
     		$("#votCOMADRE").show('normal');
   		},function(){
			$("#votCOMADRE").hide('normal');
	   	});
		$("#COMPUMASTER").toggle(function(){
     		$("#votCOMPUMASTER").show('normal');
   		},function(){
			$("#votCOMPUMASTER").hide('normal');
	   	});	
 	});
