use compushow;

insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPUPAPI','El mister de la carrera');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPUMAMI','La miss de la carrera');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPULOVE','Los computistas inseparables');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPUCARTOON','El computista que tiene un doble dibujado');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPUCHINAZO','La persona con la mente inconsciente mas cochina.');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPUADOPTADO','La persona que es quasi computista');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPULOLAS','Los cocos de la carrera');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPUBUTT','El backend de la carrera');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPUPREGUNTON', 'El computista más fastidioso en el salón de clase');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPUMORFEO','El computista que se duerme incluso en clases que no son del profesor Em..');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPUCHACARRON','El computista al que no se le entiende nada.');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPUPRODUCTISTA','Nos remitimos a videos de compushow pasados');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPADRE','El computista mas pana');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMADRE','La computista mas panita');
insert into CATEGORIA (nombreC, descripcion) VALUES ('COMPUMASTER','El mejor profesor.');

insert into PERFIL(carnetP, nombreP, apellidoP) values(01 ,'Prof Soraya',  'Abbad');                   
insert into PERFIL(carnetP, nombreP, apellidoP) values(02 ,'Prof Angela',  'Diserio');
insert into PERFIL(carnetP, nombreP, apellidoP) values(03 ,'Prof Blai',    'Bonet');
insert into PERFIL(carnetP, nombreP, apellidoP) values(04 ,'Prof Carlos',  'Figueira');
insert into PERFIL(carnetP, nombreP, apellidoP) values(05 ,'Prof Carolina','Chang');
insert into PERFIL(carnetP, nombreP, apellidoP) values(06 ,'Prof Diego',   'Mosquera');
insert into PERFIL(carnetP, nombreP, apellidoP) values(07 ,'Prof Edna',    'Ruckhaus');
insert into PERFIL(carnetP, nombreP, apellidoP) values(08 ,'Prof Ernesto', 'Mendez');
insert into PERFIL(carnetP, nombreP, apellidoP) values(09 ,'Prof Emilio',  'Hernandez');
insert into PERFIL(carnetP, nombreP, apellidoP) values(10 ,'Prof Ernesto',    'Novich');
insert into PERFIL(carnetP, nombreP, apellidoP) values(11 ,'Prof Gabriela','Montoya');
insert into PERFIL(carnetP, nombreP, apellidoP) values(12 ,'Prof Gaby',    'Escuela');
insert into PERFIL(carnetP, nombreP, apellidoP) values(13 ,'Prof Hilmar',  'Castro');
insert into PERFIL(carnetP, nombreP, apellidoP) values(14 ,'Prof Ivette',  'Martinez');
insert into PERFIL(carnetP, nombreP, apellidoP) values(15 ,'Prof Jesus',   'Ravelo');
insert into PERFIL(carnetP, nombreP, apellidoP) values(16 ,'Prof Jose',    'Cadenas');
insert into PERFIL(carnetP, nombreP, apellidoP) values(17 ,'Prof María',   'Vidal');
insert into PERFIL(carnetP, nombreP, apellidoP) values(18 ,'Prof Mariela', 'Curiel');
insert into PERFIL(carnetP, nombreP, apellidoP) values(19 ,'Prof Oscar',   'Meza');
insert into PERFIL(carnetP, nombreP, apellidoP) values(20 ,'Prof Guillermo''Palma');        ,
insert into PERFIL(carnetP, nombreP, apellidoP) values(21 ,'Prof Ricardo', 'Gonzalez');
insert into PERFIL(carnetP, nombreP, apellidoP) values(22 ,'Prof Soraya',  'Carrasquel');
insert into PERFIL(carnetP, nombreP, apellidoP) values(23 ,'Prof Victor',  'Theoktisto');
insert into PERFIL(carnetP, nombreP, apellidoP) values(24 ,'Prof Victor',  'Theoktisto');
insert into PERFIL(carnetP, nombreP, apellidoP) values(25 ,'Prof Prof',    'Pereira');
insert into PERFIL(carnetP, nombreP, apellidoP) values(26 ,'Prof Xiomara', 'Contreras');
insert into PERFIL(carnetP, nombreP, apellidoP) values(27 ,'Prof Jesus',   'de Oliveira');
insert into PERFIL(carnetP, nombreP, apellidoP) values(28 ,'Prof Patricia','Guerrero');
insert into PERFIL(carnetP, nombreP, apellidoP) values(29 ,'Prof Yudith',  'Cardinale');   

 insert into PERFIL (carnetP, apellidoP, nombreP) values(9931691,   'Duque Narvaez','Jorge E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(9931744,   'Flaviani Guastaferro','Federico');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(9932385,   'Torres Bolivar','Juan C');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0033116,   'Morandi Suárez','Carlos José');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0033279,   'Rodríguez Brasicott','Claudia Carolina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0133737,   'Cova Nuñez','Nicolas F');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0134014,   'Lacruz Lopez','Aquiles Alberto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0134514,   'Valles Rojas','Victor J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0234729,   'Carbonell Gonzalez','Luis T');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0234742,   'Castellanos Abril','Yannixia P');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0234817,   'Da Silva','Manuel A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0234826,   'De Jesus','Jose Joel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0234827,   'DeLa Cruz','Edward José');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0234832,   'De Oliveira','Cynthia G');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0234888,   'Felaco Duran','Mario Alberto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0234964,   'Gómez LaRoque','Carlos Morel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0235027,   'Hernandez Borges','Pablo C');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0235138,   'Márquez Vásquez','Ricardo Augusto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0235297,   'Pino Betancourt','Javier A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0235345,   'Ramos Moukel','Jorge Antonio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0235364,   'Rivera Ura','Jean Carlo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0235458,   'Sevilla Martínez','Alejandra delValle');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0235493,   'Tocco Di','Fazio  Ricardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0235503,   'Trujillo Williams','Rubén Darío');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0335612,   'Aguero García','Arturo Javier');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0335643,   'Artigas Caires','Maria Victoria');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0335697,   'Borrero Hermoso','Carlos Raul');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0335733,   'Camacho Valles','Leonard Ernesto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0335752,   'Casique Llanos','Gabriel R');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0335833,   'DeLlano Almarza','Luis Enrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0335839,   'Deniz Vigil','Pedro Miguel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0335858,   'Diz Montaño','Daniela');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0335867,   'Elneser Montiel',' Boris');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0335993,   'Grimán Cachutt','Lilian Caribay');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336039,   'Hernández Ruiz','Alejandro José');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336048,   'Hidalgo Sulbaran','Maria Gracia');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336049,   'Hollando Dubuc','Mauricio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336052,   'Hualde Oanes','Angel Jose');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336092,   'Laviosa Noguera','Luis Alberto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336097,   'Leger Julmeus','McArthur I');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336193,   'Millan Martinez','Diego Rafael');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336221,   'Morfe Medina','Carlos E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336224,   'Moros Carvallo','Daniel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336270,   'Pabon Briceño','German A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336319,   'Peña Duran','Jofran');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336381,   'Reyes Mejia','Mauricio Aly');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336383,   'Riccio Paredes','Hector Gabriel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336385,   'Rico Duran','Nakarid C');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336440,   'Rojas Vivas','Simón Antonio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336451,   'Romero Urdaneta','Carlos Alberto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336469,   'Salazar Spinetti','Andres Eduardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336486,   'Sanjuán Ferro','Cristina Isabel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336514,   'Simoes Ferreira',' Richard');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336630,   'Zurbaran Medina','Maria Daylen');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0336644,   'Natera Quijada','Silma Betsabeth');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436652,   'Abreu Corrales','Juan Carlos');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436653,   'Acevedo Trinimar','J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436674,   'Álvarez Pájaro','Yasmin María');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436682,   'Antunes Jimenez',' David');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436708,   'Ayaach Arruebarrena','Faríd José');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436721,   'Barrera Garcia','Andres Emiliano');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436723,   'Barreto Nava','Daniel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436771,   'Briceño Hinojosa','Gustavo Javier');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436790,   'Campa Moerbeeck','Juan G');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436808,   'Carrasquel Blanco','Arquimedes D');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436814,   'Carrizales Castro','Gerardo Enrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436817,   'Castillo Balleza','Carlos E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436834,   'Cestari Soto','Daniel Jesus');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436838,   'Chacon Orellana','Maria G');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436845,   'Cherchi Basmagi','Giovanni Paolo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436867,   'Cortejoso Shiera','Eduardo Enrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436882,   'Dambrosio Rupp','Stefano');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436886,   'DeFreitas Contreras','Jose Eduardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436905,   'Delgado Serrano','Christian E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436949,   'Faria Braz','Carlos Eduardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436975,   'Ferrer Agnone','María Sol');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0436995,   'Fung Tian','Zheng Yuan');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437024,   'Giannandrea Romero','Jose L');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437060,   'Gonzalez Gonzalez','Liseth A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437072,   'Granadillo Godoy','Ismael A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437105,   'Henriquez Herrera','Edgar Eduardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437117,   'Hernandez Rodriguez','David Manuel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437121,   'Herrera Garcia','Claudia Elena');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437127,   'Huchet Sojo','Gabrielle Andreína');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437161,   'Laya Diaz','Roicel O');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437185,   'Lopez Jimenez','Yumer A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437187,   'Lopez Orozco','Joselyn Cristal');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437189,   'Lopez Scutaro','Carlo X');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437210,   'Malledo Caraballo','Jesus Diego');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437225,   'Mariño Osorio','Andres');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437228,   'Marques Pena','Gabriela');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437248,   'Martinez Nuñez','Jacobo A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437261,   'Matheus Camacho','Elias Ernesto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437265,   'Matos Merlo','Andres Eduardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437292,   'Merino Mego','Eduardo Stefano');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437332,   'Muñumel Mesa','Gabriel David');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437385,   'Patrizio Machado','Robert Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437389,   'Pedroza Perez','Daniel A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437447,   'Quintana Barillas','Jesus Rafael');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437465,   'RangeL Arvelo','Jose F');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437469,   'Rascheri Rojas','Robert R');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437480,   'Riera Sanchez','Jose H');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437484,   'Rivas Hernandez','Jose F');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437494,   'Rivero Velasquez','Victor J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437507,   'Rodriguez Gomez','Alejandro Jose');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437542,   'Rondon Balza','Maximiliano');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437545,   'Rondon Osorio','Jesus A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437581,   'Sanchez Fumero','Jose Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437594,   'Sarda Silva','Andreina B');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437615,   'Silva Dominguez','Sergio Gabriel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437653,   'Torres DeLasHeras',' Ruben');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437654,   'Torres Faria','Daniela A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437662,   'Trindade Tuñon','Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437678,   'Valero Cianciarullo','Gianpaolo A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437686,   'Vargas Diaz','Javier E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437698,   'Velorio Shigueto','Sergio Jose');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437716,   'Vintimilla Tamasaukas','Maria E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437749,   'Meinhardt Musci','Eduardo A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0437786,   'MORALES JAIMES','DARRY ALEJANDRO');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0537795,   'Aguilar Jaime','Ellery S');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0537821,   'Ambrosio Gomez','Miguel M');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0537832,   'Aponte DelReal','Pablo A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0537836,   'Aponte Novellino','Jose Luis');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0537838,   'Aranguren Lattuf','Marlin A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0537840,   'Arellano Gonzalez','Jormar M');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0537843,   'Arevalo Valverde','Ruben E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0537846,   'Arias Rivera','Vanessa A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0537861,   'Ascencion Sanabria','Minty P');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0537862,   'Asmadt Calderon','Carlos David');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0537876,   'Baldacci Riobueno',' Carlo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0537947,   'Cabezas Medina','Alexander');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0537986,   'Carrero Rodriguez','Josmary S');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538016,   'Cerqueiro Garcia','Adriana');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538019,   'Chacon Caringella','Alessandro E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538025,   'Chacon Rangel','Reinaldo J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538034,   'Chomiak Moretti','Christian A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538039,   'Cifuentes Sans','Juan Enrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538050,   'Cordova Candedo','Andres R');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538053,   'Crer Frances','Maria E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538062,   'Da Costa',' Leonardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538064,   'Da Rocha','Marcel S');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538068,   'Da Silva','Katherine R');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538072,   'De Abreu','Molina Julio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538076,   'De Ascencao','Yessica M');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538084,   'De LosRios','Miguel A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538087,   'De Ponte','Victor M');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538102,   'Dempaire Delascio','Carlos L');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538104,   'Devis Matheus','Yanet Gabriela');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538108,   'Diaz Garcia','Eliud Timothy');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538122,   'Dipuglia Chacon','Adrian A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538134,   'Duque Zuloaga','Cristian C');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538161,   'Fariñas Fumero','Jessica Alejandra');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538163,   'Fernandez Miras','Sabrina M');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538180,   'Franchini Melo','Carla');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538194,   'Gamarra Ramirez',' Ivanhoe');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538199,   'Garcia Badaracco','Jorge David');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538235,   'Gómez Chacón','Manuel Ignacio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538246,   'Gonzalez Arreaza','Mireya Carolina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538263,   'Gonzalez Perez','Daniel Ignacio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538294,   'Guilarte Castellanos','Hector Alfredo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538328,   'Hernandez Sousa','Luis Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538334,   'Heuer Rodriguez','Guillermo J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538375,   'Krentzien De','Sola Jorge');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538402,   'Level Ruiz','Ernesto Alfonso');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538421,   'Lopez Monroy','Hector Arquimedes');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538444,   'Lyon Gonzalez','David Vicente');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538524,   'Mejia Moreno','Armando');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538538,   'Mendoza Blanco','Jose Eduardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538564,   'Monascal Capdevielle','Maria G');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538565,   'Monasterios Garcia','Gerardo A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538572,   'Montilla Linares','Abraham R');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538577,   'Mora Cardinales','Marcos J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538595,   'Moreno Briceño','Carlos D');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538632,   'Noguera Middleton','Christopher E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538641,   'Ocando Gomez','Suhaily');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538646,   'Ordoñez Diaz','Franz Antonio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538674,   'Palhazi Cuervo','Albin Daniel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538675,   'Pantic Perez','Kristoffer');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538680,   'Paredes Toro','Alexandra E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538683,   'Parra Girado','Jacob R');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538723,   'Perez Ruiz','Carlos A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538724,   'Perez Suarez','Jessica A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538773,   'Ramirez Fagre','Violette C');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538781,   'Ramirez Villegas','Daniel E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538783,   'Ramos Pereira','Angelica L');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538799,   'Rincon Garcia','Pedro J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538809,   'Rivero Maldonado','Alejandro D');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538826,   'Rodriguez DeSousa','Luis M');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538828,   'Rodriguez Fernandez',' Alberto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538838,   'Rodriguez Roiz','Javier J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538899,   'San Gil','Jose A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538908,   'Sanchez DePaz','Rodolfo L');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538916,   'Sanchez Mendivelso','Andres F');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538928,   'Santana Pineda','Ricardo Alfonso');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538936,   'Sarmiento Lasses','Carlos G');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538941,   'Segovia Vargas','Eli Daniel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538956,   'Simoes Centeno','Alexander J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538978,   'Tarazona Lopez','Alejandro I');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538983,   'Teran Martinez','Luis F');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538988,   'Toledo Sanelli','Maria Milagros');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0538990,   'Torre Mora','Fernando  J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0539001,   'Tovar Lanz','Alejandro Gabriel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0539011,   'Urbina Bermudez','Jorge G');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0539020,   'Valdes Graterol','Maria Gabriela');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0539031,   'Vazquez Valdez','Nohelia J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0539033,   'Velasquez Manzanero','Fernando Jose');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0539038,   'Vera Villegas','Franklin V');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0539070,   'Zabala Sardi','Jose C');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0539078,   'Zanin Guevara','Renzo A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0539081,   'Zerpa Rivas','Fernando E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639116,   'Aguiar Goncalves',' Karina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639128,   'Alcantara Salazar','Francis J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639141,   'Alvarez Divo','Carlos Eduardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639197,   'Balestrini Cedeño','Ivan D');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639206,   'Barretta Paramo','Rafael Jose');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639207,   'Barrios Aparicio','Liliana Leonor');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639223,   'Benitez Marcano','Emily G');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639239,   'Blanco Lopez','Natalya G');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639312,   'Carambula Cruz',' Marion');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639345,   'Cedeño Camacho','Adyari Osmari');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639366,   'Ciuffi Alvarez','Daniel A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639371,   'Coello Quiñonez','Yngrid D');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639380,   'Colmenares Rojas','Carlos A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639385,   'Conti Rizzo','Gian F');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639435,   'De Ponte','Dayana Marlene');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639437,   'De Simone','Giuseppe Saul');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639439,   'De Sousa','Alexander J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639473,   'Do Nascimiento','Mora Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639485,   'Drago Colmenares',' Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639495,   'Escorche Querales','Jose L');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639509,   'Fariña Fernandez',' Daniel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639521,   'Fernandez Fajardo','Kevin A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639538,   'Fiorillo Verenzuela','Jose Francisco');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639545,   'Franchini Melo','Roberto Gerson');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639546,   'Francisco Agra','Abel Josue');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639548,   'Franco Graterol','David E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639550,   'Franco LaRosa','Juan Carlos');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639553,   'Freytes Teixeira','Martin J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639559,   'Fundaro Garcia',' Lorenzo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639563,   'Gallardo Mosqueda','Alfredo A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639585,   'Garcia Rivas','Juan D');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639590,   'Garrido Sirit','Jose J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639609,   'Gomez Cermeño','David E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639617,   'Gomez Oramas','Consuelo Y');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639620,   'Goncalves Rodrigues','David Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639658,   'Gonzalez Vivas','Marianny C');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639661,   'Gouveia Figueira','Jesus H');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639692,   'Gutierrez Hernandez','Leonardo S');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639693,   'Gutierrez Herrera','Hector Leonardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639697,   'Gómez Fajardo','Antonio Rafael');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639699,   'Harris Breto','Ulises P');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639715,   'Hernandez Gonzalez','Daniela D');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639724,   'Hernandez Villegas','Cesar R');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639726,   'Herrera S','Fernando E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639729,   'Hidalgo Aular','Saul Samir');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639731,   'Hidalgo Mora','Richard J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639741,   'Ibarra Salas','Alexis R');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639749,   'Jaber DeLima','German Eduardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639768,   'Labbad Yousef','Jose Angel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639770,   'Labrador Jimenez','Maria A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639780,   'Leal Gonzalez','Eleazar Enrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639791,   'Leon Yepez','Juan A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639796,   'Libretti Cossio','Laura');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639810,   'Lopez Artiles','Gabriel Benito');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639812,   'Lopez Dandria','Hilda Marina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639821,   'Lopez Vivas','Julio Daniel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639843,   'Manzanares Marquez',' Javier');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639856,   'Mariño Espinoza','Williams B');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639875,   'Martucci Casanova',' Leonardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639883,   'Mañan Paolone','Nicolas Eduardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639889,   'Medina Perez','Sergio Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639902,   'Mendillo Cabrera',' Eric');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639903,   'Mendonca Teixeira','Ismael R');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639911,   'Mendoza Solarino',' Andrea');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639918,   'Meza Mendoza','Jhonathan J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639928,   'Molina Leon','Gabriela C');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639932,   'Moniz Naveda','Martha G');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639936,   'Montero Garcia','Hebert E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639945,   'Moreau Velasco','Sergio A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639953,   'Moya Prieto','Johann A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639956,   'Mundo Perez','Antonio F');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639961,   'Muñoz Peñaranda','Nicolas J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639965,   'Nebiolo Navidad',' Giancarlo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639990,   'Omaña Arraiz','Roberto A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0639992,   'Omaña Velazquez','Omar Alberto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640004,   'Osuna Salgado','Josue M');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640032,   'Pastorelli Castillo','Gustavo L');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640037,   'Paytuvi Egui','Rafael H');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640044,   'Pellegrino Di','Stefano     Alessandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640046,   'Perdomo Morales','Angel E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640048,   'Pereira Espinoza','Alechandrina J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640049,   'Pereira Goncalves','Cecilia A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640058,   'Perez Fernandez','Ariana I');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640072,   'Perez Peñaranda','Linda R');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640073,   'Perez Poggioli','Manuel G');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640095,   'Pimentel Ripanti','Leopoldo J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640108,   'Ponte Betancourt','Federico  Ignacio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640130,   'Quintero Diaz','Angel H');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640159,   'Reyes Venezia','Patricia C');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640174,   'Rivas Social','Jolimar J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640189,   'Rodriguez Alvarez','Carlos L');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640193,   'Rodriguez Boscan','Einis I');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640199,   'Rodriguez Drumond','Francisco A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640206,   'Rodriguez Gomez','Rafael E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640232,   'Rodriguez Viafara','Hetsy Milagros');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640233,   'Rodriguez Villegas','Ronier A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640234,   'Rodriguez delVillar','Trimarchi  Daniel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640254,   'Ros DosSantos', 'Alfonso');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640261,   'Rubilar Gonzalez','Maria Gabriela');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640263,   'Rubio Villarreal','Angel David');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640273,   'Ruiz Uzcategui','Daniela A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640294,   'Samaniego Revilla','Katty E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640309,   'Sanchez Tabares','Alberto Luis');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640314,   'Santivañez Solano','Wendy Ysabel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640342,   'Socorro Gil',' Christian');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640351,   'Sosa Salazar','Luis E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640358,   'Sparano Videtta','Gabrielle S');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640377,   'Todisco Lopez','Lorenzo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640386,   'Torres Tovar','Jesus Manuel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640414,   'Valera Guzman','Karina J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640431,   'Veitia Pernalete','Guillermo A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640433,   'Velasquez Conde','Daniela A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640446,   'Vergara Ramiro','Giovanni');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640459,   'Villasana Muñoz','Cesar R');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0640476,   'Yamaui Gonzalez','Alexandra Carolina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740568,   'Alvarado Virag','Ana Cristina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740602,   'Armas Velasquez','Virginia Sofia');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740608,   'Ascanio Soto','Augusto José');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740619,   'Baldizan Llanes','Oriana J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740625,   'Barber Pietri','Harold');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740632,   'Bartoli Bracho','Samuel Enrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740638,   'Becerra Blanco','Juan Carlos');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740639,   'Belesaca Jimenez','Cecilia Z');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740643,   'Beltrami Mcquattie','Hector Benjamin');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740644,   'Beltran DaSilva','Rafael Antonio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740681,   'Bruzual Balzan','Daniel José');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740718,   'Carpio Castellanos',' Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740728,   'Castellanos Barroeta','Kysbel Andreina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740732,   'Castillo Jaspe','Katiana Ysabel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740737,   'Catari Leidenz','Jose Miguel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740767,   'Coello Coraspe','Katyuska Carolina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740777,   'Contreras Guanda','Jhosbert Abraham');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740789,   'Croes Mendez',' Carolina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740817,   'DeValery Fiorito','Rene Vicente');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740819,   'DelRio Rodriguez','Mónica Mercedes');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740845,   'DosRamos Yanez','Erick Gildo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740851,   'Duran Klie','Gabriel A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740855,   'El Assaad','Omar Alí');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740888,   'Fernandez Correia','Kelwin');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740895,   'Ferreira Pinto','Katherine Susan');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740897,   'Ferrero Romero','Andres Eduardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740902,   'Fiol Locantore','Edgar Giovanni');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740913,   'Franco Carvajal','Angel Roso');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740915,   'Freitas DeFreitas','Cesar Enrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740919,   'Gabidia Garcia','Carlos Alberto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740926,   'Garban Garcia','Cesar Eduardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740930,   'Garcia Aguilera','Victor M');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740951,   'Gimenez Perez','Ezequiel Elias');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740979,   'Gonzalez Leal','Johan Isaias');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0740984,   'Gonzalez Peñuela','Federico Andrés');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741010,   'Gutierrez Gherbaz','Pedro Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741016,   'Guzman Moreno','Jose Manuel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741038,   'Hernandez Quijada','Veronica');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741051,   'Huga Labarca','Carlos Alberto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741054,   'Iglesias Moreno','Jose Luis');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741057,   'Irahola Ramirez','Nellybett Andrea');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741063,   'Jilo Ghazal','Maria Isabel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741087,   'Lanza Garcia','Maria Francys');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741092,   'Lattke Urbaneja','Tony Enrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741104,   'Lezama Gonzalez','José Gregorio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741108,   'Lo Huang','Jose L');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741109,   'Lo Monaco','Lucia Mariana');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741120,   'Lopez Procopio','Isaac Esteban');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741125,   'Loriente Caiazzo','María Andreina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741126,   'Lovera Torres','Fernando Andrés');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741130,   'Lucero Guerrero','Erwin Fabian');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741138,   'Machado Gonzalez',' Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741150,   'Manrique Cruz','Nestor Roman');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741154,   'Marcano Zambrano','Andreina DelVa');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741165,   'Martinez Gedler','Gaudy Karelis');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741174,   'Martini Goncalves','Maria Alejandra');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741185,   'Medina Mago','Nelson E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741198,   'Melo Chirinos','Jaidibeth A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741202,   'Mendez Hernandez','Jesus Eduardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741206,   'Mendoza Bollam','Brian Marcial');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741249,   'Moreno Correa','Jonathan J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741253,   'Morillo Muñoz','Audry Vanessa');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741260,   'Muñoz Medina','Anselmo Jose');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741268,   'Navarro Mollejas','Luis Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741279,   'Nowacka Barros',' Marilyn');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741286,   'Ochoa Pastrán','Charles Heliot');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741295,   'Oropeza Rodriguez','Narbelys Catterin');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741302,   'Pacheco Gonzalez','María Leonor');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741311,   'Parada Gamboa','Alvaro Jesus');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741329,   'Perez Camacho','Dennis Esteban');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741330,   'Perez Camargo','Oliver Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741331,   'Perez Carta','Harold José');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741340,   'Perez Pirela','José Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741345,   'Pesate Temprano','Mike');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741358,   'Pimentel Guerra','Victoria');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741362,   'Pinedo Camacho','Abelardo Agustin');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741378,   'Porco Rametta','Aldo Fabrizio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741384,   'Preciado Llanos','Alejandra Alhelí');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741420,   'Reggio Gallen','Fabiana Eloisa');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741423,   'Reina Mayora','Saymar Milagros');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741431,   'Ricchiutti Urresti','Jon Ander');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741432,   'Rico Escalante','Rene David');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741468,   'Rodriguez Porras','Manuel Alfonso');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741475,   'Rodriguez Tinoco','Daniel Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741502,   'Rosas Ramirez','Juan V');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741510,   'SANDOVAL ANGULO','FRANK J');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741573,   'Soto Martin','Alejandro Alberto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741582,   'Subero Oberto','David Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741591,   'Timaury Moreno','Carlos E');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741604,   'Tough Guardia','Alexander Daniel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741612,   'Urbina DeMiguel','Christian Alexander');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741618,   'Vainberg Gauna','Diana Karina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741629,   'Varela Verrilli','Krisvely Coromoto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741639,   'Velazquez Mulato','Levi Noel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741651,   'Vieira Zambrano','Luis Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741652,   'Viejo Sanz','Ileana Lorena');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741654,   'Viera Araujo','Nilver Fernando');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741664,   'Virguez Delepiani','Ricardo Alberto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741672,   'Wilhelm Garcia','Andreina Simonett');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741677,   'Zambrano Quintero','Edward Luciano');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741711,   'Rivas Silva','Arturo A');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741722,   'La Russa','Fabio José');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741725,   'Valera DelPino','Daniel Fernando');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741895,   'Ruiz Campos','Rosannys Carolina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0741896,   'Chitty Morales','Carlos José');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810057,   'Araujo Alvarez','Eleazar Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810086,   'Azocar Carrasquel','Daniel Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810090,   'Ballesta Estrada','Alejandro José');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810178,   'Caprioli Murillo',' Alberto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810200,   'Castillo Cacua','Carlos Manuel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810215,   'Cespedes Vargas','Fernando Enrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810220,   'Chang Chu','Kidjou Argenis');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810223,   'Charara Charara','Susana');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810243,   'Contreras Chacon','Roque Daniel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810253,   'Cossio Ramirez',' Alejandra');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810272,   'DApollo Rodriguez','Jose Henrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810281,   'De Andrade','Paulo Fabrizio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810323,   'Dos Reis','Jennifer');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810337,   'Esparragoza Sanchez','Luis Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810371,   'Filardi Vera','Niuroska Andreina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810383,   'Freites Melero','Gabriel Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810398,   'Garbi Moya','Alejandro Jose');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810406,   'Garcia Figueira','Andreina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810443,   'Gollini Peraza','Andres Alexander');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810451,   'Gomez Papotto','Carlos Enrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810455,   'Goncalves DaSilva','Jose Alberto');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810462,   'Gonzalez Canonico','Betzabeth Carolina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810479,   'Goudet Diaz','David Enrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810515,   'Gyomrey Leal','Andras Albert');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810519,   'Hannani Delgado','Roshanak');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810551,   'Hitti Ratino',' Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810558,   'Iribarne Requeira','Maria Valentina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810564,   'Jaimes Parilli','Diego Esteban');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810581,   'Kristek Kristek','Michelle Alexandra');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810588,   'Landaeta Casanova','Edwar Jesus');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810602,   'Ledezma Rondon','Carlos Guillermo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810608,   'Leon Quinteiro',' Juliana');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810611,   'Leon Zapata','German Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810622,   'Lobo Perez','Daniel Enrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810638,   'Lopez-Torres Stadler','Miguel angel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810655,   'Lunar Fuentes','Ricardo Enmanuel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810667,   'Mallcott Alvarez','Daniel Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810672,   'Manzano Marano','Octavio Jesus');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810697,   'Martinez Leo','Gabriela Andreina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810704,   'Martinez Vargas','Jesus Armando');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810708,   'Masrie Adoumich','Abdalah');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810722,   'Medrano Navarro','Agustin Ignacio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810729,   'Melian Mizrahi','Jonathan Mauricio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810734,   'Mendoza Bastidas','José Noel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810762,   'Montenegro Diaz','Daniel Arturo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810774,   'Moreno Mago','Miguel Arturo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810790,   'Murillo Paez','Arturo Miguel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810792,   'Nardone Gonzalez',' Carla');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810798,   'Niño Diaz','Estephany');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810801,   'Nori Gonzalez','Franco Gabriel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810804,   'Nuñez Michelena','Andel');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810845,   'Parra Saavedra','Adriana Zuray');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810852,   'Peñaranda Peñaranda','Roso Antonio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810860,   'Pereira Guerra','Geraldine Andrea');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810881,   'Pinto Andrades','Aquilino Enrique');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810885,   'Piñate Martinez','Diego Isaac');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810918,   'Ramos Belisario','Maria Jose');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810921,   'Ramos Thomas','Leonardo Rafael');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810965,   'Rodriguez Morales','Ernesto Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810971,   'Rodriguez Pomenta','Jose Antonio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0810992,   'Romero DeAbreu','Pedro Antonio');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0811003,   'Rondon Sosa','Isaac Jacobo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0811005,   'Rosa Delgado',' Ricardo');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0811021,   'Russo Gabriel','Alejandro');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0811027,   'Sahmkow Beicos','Fernando Andres');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0811031,   'Salazar Garofalo','Andreth Rafael');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0811044,   'Santacoloma Blanco','Vicente Fernando');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0811069,   'Sifontes Castro','Rafael Jesus');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0811094,   'Stornelli Ortega','Bishma Radheya');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0811149,   'Valdez Romero','Jenny Daniela');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0811186,   'Villalobos Perez',' Cristina');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0811196,   'Viña Bello','Juan Carlos');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0811208,   'Yuan Chen','Charles Ketuig');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0811369,   'Pérez Iranid','del Carmen');
 insert into PERFIL (carnetP, apellidoP, nombreP) values(0911265,   'Morón Venegas','Yusmell Carolina');
